### ISSUE TITLE
Return created and updated params for space on the GraphQL API

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#166]

**Comment by stormsson** [comment]
I'd like to consider this task; could I have more info ?

**Comment by mktcode** [comment]
@stormsson it just needs to be added here: https://github.com/snapshot-labs/snapshot-hub/blob/fa64304a1905e3edb7dde6d7a044ffb2fc65b998/src/graphql/schema.gql#L187-L211

**Comment by stormsson** [comment]
I have at the moment what I think is a working branch with the task, but I'm still examining and testing: 
I think  it's not possible to simply use  `select *`:

almost every entity that has a relation with space  uses `formatSpace` inside the formatter:

- formatProposal
- formatVote
- formatFollow
- formatSubscription


in order to have created_at, updated_at available, the entities queries too must be modified:
for example from 
```
const query = `
    SELECT s.*, spaces.settings FROM subscriptions s
    INNER JOIN ......
  `;
```
to 
```
const query = `
    SELECT s.*, spaces.settings, spaces.created_at, spaces.updated_at FROM subscriptions s
    INNER JOIN ......
  `;```


if you use `select spaces.*` you have a naming conflict because both tables s and spaces have a column `id`, and latter overwrites the former .

it has spectacular results: when the frontend queries the hub, every single entity ID is instead replaced by the space id
