### ISSUE TITLE
Move away from IPNS and use ENS text record just to store controller

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-hub#412]

**Comment by ChaituVR** [comment]
Do we want to remove this alternate way of creating space? 

https://docs.snapshot.org/spaces/create/alternative-way-to-create-a-space

**Comment by bonustrack** [comment]
@ChaituVR both, please write some specs before coding so we can agree on the approach

**Comment by ChaituVR** [comment]
- On UI, In the "Set space controller" step, set the text record to `${controllerAddress}` instead of IPNS
- On UI and hub, to update space settings, check if the text record exists in the following format:
   - `ipns://storage.snapshot.page/registry/${networkPath}${body.address}/${spaceIdUri}` (In future we can announce and disable this check)
   - `${controllerAddress}`
- On the hub, Remove fleek upload to 'snapshot-team-bucket'
- Make sure the `/poke` route is working well to update space settings from IPFS and for others to return an error

**Comment by ChaituVR** [comment]
@bonustrack Can confirm?

**Comment by zzuziak** [comment]
Hi @ChaituVR @bonustrack, what's the status of this issue? 🙏

**Comment by ChaituVR** [comment]
https://github.com/snapshot-labs/snapshot/issues/3472 is more related now, will close this one
